<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    public function run()
    {
        $teams = [
            [
                'id' => 894,
                'name' => 'Gentbrugge Allstars',
                'first_name' => 'Bas',
                'last_name' => 'Coupé',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'wit',
                'shorts_color' => 'blauw',
                'team_info' => "We zijn als vriendenploegje begonnen in 2009 in derde provinciale futsal Oost-VLaanderen, maar na 9 seizoenen vonden we het tijd voor een iets minder competitieve en - hopelijk :-) - qua niveau iets lichtere competitie.\n\nAmbities: elke week een leuk matchke spelen en een beetje in beweging blijven :)\n\nPalmares:\n\nSEIZOEN 2009-2010: 3 PROVINCIAAL G: 8e plaats\nSEIZOEN 2010-2011: 3 PROVINCIAAL F: 9e plaats\nSEIZOEN 2011-2012: 3 PROVINCIAAL F: 11e plaats\nSEIZOEN 2012-2013: 3 PROVINCIAAL E: 3e plaats\nSEIZOEN 2013-2014: 3 PROVINCIAAL B: 2e plaats\nSEIZOEN 2014-2015: 3 PROVINCIAAL A: 4e plaats\nSEIZOEN 2015-2016: 3 PROVINCIAAL A: 7e plaats\nSEIZOEN 2016-2017: 3 PROVINCIAAL A: 5e plaats\nSEIZOEN 2017-2018: 3 PROVINCIAAL B: 9e plaats\nSEIZOEN 2018-2019: LZV CUP, 1e klasse GENT: 7e plaats\nSEIZOEN 2019-2020: LZV CUP, 1e klasse GENT: 12e plaats (degradatie door niet afwerken competitie)\nSEIZOEN 2020-2021: LZV CUP, 2e klasse GENT: / iets met corona\nSEIZOEN 2021-2022: LZV CUP, 2e klasse GENT: 4e plaats\nSEIZOEN 2022-2023: LZV CUP, 2e klasse GENT: 5e plaats\nSEIZOEN 2023-2024: LZV CUP, 2e klasse GENT: 12e plaats",
                'delay_home_max' => 10,
                'delay_days_home_max' => 0,
                'delay_days_away_max' => 0,
                'created_at' => '2018-08-22 12:10:35',
                'updated_at' => '2024-05-31 10:31:14',
                'last_login_at' => '2024-11-26 22:39:39',
            ],
            [
                'id' => 2043,
                'name' => 'The Waffels',
                'first_name' => 'Kimberly',
                'last_name' => 'De Scheemaecker',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Blauw rood',
                'shorts_color' => 'Zwart',
                'team_info' => "Sportieve jonge ploeg dat open staat voor uitdagingen",
                'delay_home_max' => 9,
                'delay_days_home_max' => 9,
                'delay_days_away_max' => 9,
                'created_at' => '2023-09-04 23:22:13',
                'updated_at' => '2023-11-22 22:01:12',
                'last_login_at' => '2024-11-23 19:42:39',
            ],
            [
                'id' => 1791,
                'name' => 'YoungStars United',
                'first_name' => 'Björn',
                'last_name' => 'Van Audenaerde',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Fluo Groen  (Alt Grijs)',
                'shorts_color' => 'Wit.     (Alt Grijs)',
                'team_info' => "Hallo,\n\nGraag stel ik ons even voor. Wij zijn ZVC Youngstars United een vriendengroep die dezelfde passie hebben onder het voetballen.\nWe zijn een beginnend voetbal team en waaronder ons eerste seizoen hier in de LZV cup competitie.\nWe hebben geen verwachtingen voor dit seizoen omdat we niet weten aan wat we ons mogen verwachten qua niveau.\nWe hopen toch in ieder geval op een mooi resultaat aan het einde van het seizoen.\nMaar het belangrijkste voor ons is om te voetballen waar fair play en respect van beide teams naar elkaar toe aanwezig is tijdens de wedstrijd.",
                'delay_home_max' => 4,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 1,
                'created_at' => '2022-08-20 21:09:08',
                'updated_at' => '2024-10-13 16:45:37',
                'last_login_at' => '2024-11-20 15:30:50',
            ],
            [
                'id' => 2040,
                'name' => 'Earthfield',
                'first_name' => 'Bart',
                'last_name' => 'De Vlieger',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'donkerblauw',
                'shorts_color' => 'wit',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 3,
                'delay_days_away_max' => 2,
                'created_at' => '2023-09-04 23:22:13',
                'updated_at' => '2024-08-20 21:23:10',
                'last_login_at' => '2024-11-26 14:19:47',
            ],
            [
                'id' => 962,
                'name' => 'Kymkoi Superboys',
                'first_name' => 'Jens',
                'last_name' => 'Van Hecke',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'zwart',
                'shorts_color' => 'wit',
                'team_info' => "Wij zijn ZVC Kymkoi Superboys, intussen bezig aan het zesde seizoen in de LZV Cup. We spelen vooral voor het plezier en de gezelligheid, maar de ambitie om zo hoog mogelijk te eindigen is er vanzelfsprekend ook. Doorheen de seizoenen behaalden we al een aantal mooie eindnoteringen, maar na veel hard werk en een aantal rake transfers staan we dit jaar sterker dan ooit en mogen we wat hoger mikken. We spelen natuurlijk nog altijd voor het plezier en het samenzijn, maar wie weet wat er dit seizoen uit de bus komt. Gesteund door onze loyale supportersgarde gaan we er elke week keihard tegenaan. #zvckymkoisuperboys",
                'delay_home_max' => 5,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 5,
                'created_at' => '2018-08-23 00:08:11',
                'updated_at' => '2024-03-27 17:13:54',
                'last_login_at' => '2024-11-21 13:36:50',
            ],
            [
                'id' => 893,
                'name' => 'PZC Gent',
                'first_name' => 'Ischa',
                'last_name' => 'Van Alboom',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Blauw',
                'shorts_color' => 'Blauw',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 0,
                'created_at' => '2018-08-22 12:10:35',
                'updated_at' => '2022-12-04 00:05:32',
                'last_login_at' => '2024-11-22 13:59:10',
            ],
            [
                'id' => 1387,
                'name' => 'Inter Provinciale',
                'first_name' => 'Thibault',
                'last_name' => 'Duhamel',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Lichtblauw',
                'shorts_color' => 'Wit',
                'team_info' => "Groep vrienden uit ongeveer alle Vlaamse provincies. Allemaal enorm veel goesting om te voetballen! De ploeg is samengesteld van mensen zonder ervaring tot mensen met hopen ervaring op hoger niveau.",
                'delay_home_max' => 3,
                'delay_days_home_max' => 31,
                'delay_days_away_max' => 7,
                'created_at' => '2020-08-22 09:42:15',
                'updated_at' => '2024-02-14 14:59:35',
                'last_login_at' => '2024-11-26 13:17:17',
            ],
            [
                'id' => 671,
                'name' => 'Floere Foef',
                'first_name' => 'Kris',
                'last_name' => 'Van Elsen',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Roze',
                'shorts_color' => 'zwart',
                'team_info' => "FC Floere Foef is ontstaan vanuit café 't Floere Foefke uit Gent in 1995.   Een bende vrienden richtte de club op.  22 jaar speelden we in de KBVB  (3e en 4e provinciale) en sinds 2017 lid van de LZV-cup.  Op dit moment spelen er nog steeds 3 spelers mee van het eerste uur (onze 'benjamin' is 39 jaar en 'nestor' 55 jaar - de rest daartussen en af en toe een joker....",
                'delay_home_max' => 2,
                'delay_days_home_max' => 365,
                'delay_days_away_max' => 1,
                'created_at' => null,
                'updated_at' => '2024-09-18 17:38:53',
                'last_login_at' => '2024-11-11 16:01:38',
            ],
            [
                'id' => 1374,
                'name' => 'De Rougekes B',
                'first_name' => 'Thomas',
                'last_name' => 'Vercauteren',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Bordeaux of Wit',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 12,
                'delay_days_home_max' => 4,
                'delay_days_away_max' => 365,
                'created_at' => '2020-08-22 09:35:27',
                'updated_at' => '2024-10-25 17:17:04',
                'last_login_at' => '2024-11-27 09:25:30',
            ],
            [
                'id' => 1654,
                'name' => 'Free Agents FC',
                'first_name' => 'Laurits',
                'last_name' => 'Geerardyn',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'zwart-wit',
                'shorts_color' => 'Zwart',
                'team_info' => 'IBIZA 2025',
                'delay_home_max' => 10,
                'delay_days_home_max' => 0,
                'delay_days_away_max' => 2,
                'created_at' => '2021-09-01 22:38:13',
                'updated_at' => '2024-10-28 13:31:39',
                'last_login_at' => '2024-11-25 15:58:57',
            ],
            [
                'id' => 1589,
                'name' => 'FC Foebal',
                'first_name' => 'Bram',
                'last_name' => 'Audenaert',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Zwart',
                'team_info' => "Eén sport, één team. Meerdere neuzen, één richting. Deze waarden dragen we met ons mee tot in het diepste van ons hart. Daar waar doorzetting zijn limieten kent, waar twijfel de vastberadenheid verlaat en daar waar de vaderlozen een thuisoord vinden. Daar staan wij. Met de armen om elkaar. Wij hebben geen kompas nodig om te zeggen wat we doen. Wij zijn kompassen. Wij gaan waar we ons heen brengen. Soms en altijd. Wij zijn FC Foebal. Wij staan er. Ook als we er niet zijn. Eén sport. Allen gelijk. Zeg nee tegen racisme.",
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 6,
                'created_at' => '2021-08-23 14:05:11',
                'updated_at' => '2022-03-15 11:33:01',
                'last_login_at' => '2024-11-26 20:43:24',
            ],
            [
                'id' => 2163,
                'name' => 'Cara Gent',
                'first_name' => 'Raf',
                'last_name' => 'Batselier',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Wit',
                'team_info' => "Wij als Cara Gent zijn een hechte bende waar vriendschap centraal staat, in de week voetballen we samen, int weekend durven we wel eens een pint pakken. Wij kijken ernaar uit om de andere ploegen aan het werk te zien!",
                'delay_home_max' => 3,
                'delay_days_home_max' => 7,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:46:04',
                'updated_at' => '2024-11-17 19:22:05',
                'last_login_at' => '2024-11-20 14:19:22',
            ],
            [
                'id' => 496,
                'name' => 'AC Miljaar',
                'first_name' => 'Felix',
                'last_name' => 'Windels',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'zwart/rood',
                'shorts_color' => 'zwart',
                'team_info' => null,
                'delay_home_max' => 5,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 0,
                'created_at' => null,
                'updated_at' => '2022-09-07 09:43:07',
                'last_login_at' => '2024-11-25 12:37:22',
            ],
            [
                'id' => 676,
                'name' => 'Sportus Ganda',
                'first_name' => 'Niels',
                'last_name' => 'De Bruyn',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Bordeaux',
                'shorts_color' => 'Marineblauw',
                'team_info' => null,
                'delay_home_max' => 0,
                'delay_days_home_max' => 0,
                'delay_days_away_max' => 0,
                'created_at' => null,
                'updated_at' => '2024-05-24 17:20:28',
                'last_login_at' => '2024-11-07 23:50:05',
            ],
            [
                'id' => 1588,
                'name' => 'Fazant Fazant Fazant LO',
                'first_name' => 'Bauke',
                'last_name' => 'Chaerle',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Rood',
                'team_info' => null,
                'delay_home_max' => 2,
                'delay_days_home_max' => 7,
                'delay_days_away_max' => 5,
                'created_at' => '2021-08-23 14:04:10',
                'updated_at' => '2023-08-19 11:52:12',
                'last_login_at' => '2024-11-25 23:42:48',
            ],
            [
                'id' => 1367,
                'name' => 'ZVCécémel',
                'first_name' => 'Stijn',
                'last_name' => 'Briers',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'oranje',
                'shorts_color' => 'zwart',
                'team_info' => "Onze spelers kennen elkaar van de straten in Gentbrugge waar we onder de lantaarnpalen sambavoetbal brengen en panna's zetten.\n\nWe kiezen voor een bewuste mix tussen ervaring en jong bloed. Zo krijgt onze oudste speler al grijze haren en de jongste pas schaamhaar.\n\nOnze ambitie:\nDe ambitie is kampioen spelen, het rampscenario is degraderen. De realiteit mag iets daartussen zijn.\n\nOnze kwaliteiten:\nLange ballen en Cécémel uit brik",
                'delay_home_max' => 5,
                'delay_days_home_max' => 0,
                'delay_days_away_max' => 0,
                'created_at' => '2020-08-22 09:35:27',
                'updated_at' => '2024-11-13 15:44:51',
                'last_login_at' => '2024-11-26 14:16:21',
            ],
            [
                'id' => 1903,
                'name' => 'Lootse Adonissen',
                'first_name' => 'Bram',
                'last_name' => 'Van Ryckeghem',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Goud',
                'shorts_color' => 'Zwart',
                'team_info' => "10 strijders verenigt in 1 ploeg, neen voor hen is het nooit genoeg. Met de steun van onze supporters zijn we praktisch niet te verslaan, en mocht het toch gebeuren zullen we er in de derde helft weer staan. Panna's en trucjes zijn aan ons niet besteed, maar goals scoren we bij de vleet. Ons eerste jaar eindigden we slechts in de middenmoot , maar dit seizoen is geen ambitie te groot. Een team van trainers en analisten zal ons de weg naar het kampioenschap wijzen, geen één ploeg zal met een gerust gemoed naar uytenhove afreizen.\n\nSeizoen 23/24: 1e klasse regio Gent - pl. 8",
                'delay_home_max' => 3,
                'delay_days_home_max' => 7,
                'delay_days_away_max' => 7,
                'created_at' => '2023-08-18 12:18:24',
                'updated_at' => '2024-10-23 16:19:48',
                'last_login_at' => '2024-11-27 10:25:56',
            ],
            [
                'id' => 491,
                'name' => 'Invinciboys',
                'first_name' => 'Arthur',
                'last_name' => 'Hugaert',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Groen',
                'shorts_color' => 'Wit',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 5,
                'created_at' => null,
                'updated_at' => '2024-08-17 09:39:00',
                'last_login_at' => '2024-11-27 18:14:54',
            ],
            [
                'id' => 1904,
                'name' => 'FC Belgian Delight',
                'first_name' => 'Selçuk',
                'last_name' => 'Özer',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Groen',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 14,
                'delay_days_away_max' => 14,
                'created_at' => '2023-08-18 12:18:24',
                'updated_at' => '2024-08-22 12:26:08',
                'last_login_at' => '2024-11-26 07:16:58',
            ],
            [
                'id' => 1930,
                'name' => 'Guardiola’s Classic V',
                'first_name' => 'Luka',
                'last_name' => 'Messiaen',
                'email' => 'luka@test.com',
                'website' => null,
                'shirt_color' => 'blauw',
                'shorts_color' => 'wit',
                'team_info' => "club kleuren: Blauw Wit\nZusterploeg van Guardiola's Angels\n\nPalmares Angels:\nSEIZOEN 2021-2022: 1e klasse Gent studenten: 5e plaats\nSEIZOEN 2022-2023: 1e klasse Gent studenten: 1e plaats\nSEIZOEN 2023-2024: 1e klasse Gent studenten: 1e plaats\n\nPalmares Classic:\nSEIZOEN 2023-2024: 2e klasse Gent: 2e plaats",
                'delay_home_max' => 1,
                'delay_days_home_max' => 3,
                'delay_days_away_max' => 3,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2024-11-04 12:00:23',
                'last_login_at' => '2024-11-27 11:51:14',
            ],
            [
                'id' => 1933,
                'name' => 'FC Block',
                'first_name' => 'Lars',
                'last_name' => 'Bieseman',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Groen',
                'team_info' => "Thuiswedstrijden spelen we in rode shirts en groene broekjes, uitwedstrijden in groene shirts en witte broekjes.\n\nPalmares LZV-Cup:\n- 2023-2024: Tweede klasse regio Gent: 3de plaats\n- 2024-2025: Eerste klasse regio Gent: ⏳️",
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2024-08-31 18:47:17',
                'last_login_at' => '2024-11-27 11:54:59',
            ],
            [
                'id' => 2152,
                'name' => 'Union Gent',
                'first_name' => 'Yasin',
                'last_name' => 'Kara',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Blauw',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 10,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 1,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-11-13 15:36:18',
                'last_login_at' => '2024-11-26 14:32:18',
            ],
            [
                'id' => 2048,
                'name' => 'Kipstar Academy',
                'first_name' => 'August',
                'last_name' => 'Veys',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'geel',
                'shorts_color' => 'groen',
                'team_info' => "Ontstaan: Geen coole backstory\nPalmares: Redelijk leeg\nAmbities: We willen wel eens winnen\nKwaliteiten: Supertsjille teammanager en danne keeper",
                'delay_home_max' => 5,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 2,
                'created_at' => '2023-09-12 14:36:39',
                'updated_at' => '2024-08-19 10:40:17',
                'last_login_at' => '2024-11-22 17:15:41',
            ],
            [
                'id' => 1929,
                'name' => 'VKN Melle',
                'first_name' => 'Nicolas',
                'last_name' => 'Cauhape',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'lichtblauw',
                'shorts_color' => 'lichtblauw',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 5,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2023-09-17 16:24:25',
                'last_login_at' => '2024-11-26 13:58:10',
            ],
            [
                'id' => 1123,
                'name' => 'ZVC Goal Diggers',
                'first_name' => 'Jeroen',
                'last_name' => 'Van Laecke',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart/Rood',
                'shorts_color' => 'Zwart',
                'team_info' => "ZVC Goal Diggers, opgericht door vrienden anno 2019, is meer dan een understatement op het Nevelse grondgebied en wordt wel eens hét uithangbord genoemd van het Oostbroekcomplex.\n\nVolg zeker ook onze Facebook & Instagram pagina!\nhttps://www.instagram.com/zvc_goal_diggers/\n\nSeason 2024-2025\nLet’s go\n\nSeason 2023-2024\nReady to rumble! De ploeg kende nog vele blessures bij de seizoenstart en 2 leden verlieten in de tussentijd het schip.\nDe ploeg strandde onder de promotieplaatsen.\n\nSeason 2022-2023\nEen seizoen om snel te vergeten. Op de allerlaatste speeldag lieten de Diggers het afweten tegen no. 3 in de stand en belandde de ploeg in extremis op een degradatieplaats.\n\nSeason 2021-2022\nOndanks het minste aantal tegengoals in de competitie strandde ZVC Goal Diggers op een gedeelde 4e plaats.\n\nSeason 2020-2021\nNa slechts 5 wedstrijden te hebben gespeeld, werd dit seizoen afgelast wegens corona.\n\nSeason 2019-2020\nNa de spannende seizoensontknoping en na de kampioen twee maal over de knie te hebben gelegd, strandde ZVC Goal Diggers tevergeefs op de tweede plaats in de 3e klasse A te Gent. Toch werd de inzet van haar spelers beloond met promotie naar 2e klasse.",
                'delay_home_max' => 8,
                'delay_days_home_max' => 10,
                'delay_days_away_max' => 10,
                'created_at' => '2019-08-17 11:07:22',
                'updated_at' => '2024-11-03 11:06:49',
                'last_login_at' => '2024-11-10 20:24:25',
            ],
            [
                'id' => 1905,
                'name' => 'Powerpuff FC',
                'first_name' => 'William',
                'last_name' => 'Herbert',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'wit',
                'shorts_color' => 'wit',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2023-08-18 12:18:24',
                'updated_at' => '2024-06-01 11:30:51',
                'last_login_at' => '2024-11-25 15:59:23',
            ],
            [
                'id' => 1204,
                'name' => 'Hertha Bierlijn',
                'first_name' => 'Simon',
                'last_name' => 'Van Cauwenberghe',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Blauw-wit',
                'shorts_color' => 'Blauw',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 1,
                'created_at' => '2019-08-23 17:09:46',
                'updated_at' => '2023-11-29 09:20:43',
                'last_login_at' => '2024-11-18 08:50:37',
            ],
            [
                'id' => 1591,
                'name' => 'Schalke Vul Bier',
                'first_name' => 'Simon',
                'last_name' => 'Pattyn',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Wit',
                'team_info' => null,
                'delay_home_max' => 5,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 1,
                'created_at' => '2021-08-23 14:05:11',
                'updated_at' => '2023-05-04 21:05:56',
                'last_login_at' => '2024-11-26 23:13:05',
            ],
            [
                'id' => 1917,
                'name' => 'XXX Gent',
                'first_name' => 'Seppe',
                'last_name' => 'De Clercq',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Roze',
                'shorts_color' => 'Wit',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 1,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2023-09-12 15:18:34',
                'last_login_at' => '2024-11-26 13:46:49',
            ],
            [
                'id' => 1919,
                'name' => 'Green Valley Rangers',
                'first_name' => 'Igor',
                'last_name' => 'Schepens',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Rood',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 7,
                'delay_days_away_max' => 7,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2024-09-28 14:43:51',
                'last_login_at' => '2024-11-09 22:09:28',
            ],
            [
                'id' => 1715,
                'name' => 'FC Ballie',
                'first_name' => 'Xander',
                'last_name' => 'Vermeulen',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Ice mint',
                'shorts_color' => 'zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 5,
                'created_at' => '2022-08-17 08:30:53',
                'updated_at' => '2024-09-09 10:49:16',
                'last_login_at' => '2024-11-26 08:47:35',
            ],
            [
                'id' => 1384,
                'name' => 'Rode Ster Liedeberg',
                'first_name' => 'Max',
                'last_name' => 'Louagie',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 1,
                'delay_days_away_max' => 7,
                'created_at' => '2020-08-22 09:42:15',
                'updated_at' => '2024-11-07 05:00:47',
                'last_login_at' => '2024-11-27 17:29:00',
            ],
            [
                'id' => 1655,
                'name' => "Guardiola's Angels",
                'first_name' => 'Luka',
                'last_name' => 'Messiaen',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Lichtblauw',
                'shorts_color' => 'Wit',
                'team_info' => "Palmares Angels:\n\nSEIZOEN 2021-2022: 1e klasse Gent studenten: 5e plaats\nSEIZOEN 2022-2023: 1e klasse Gent studenten: 1e plaats\nSEIZOEN 2023-2024: 1e klasse Gent studenten: 1e plaats\n\nPalmares Classic (zusterploeg):\n\nSEIZOEN 2023-2024: 2e klasse Gent: 2e plaats",
                'delay_home_max' => 3,
                'delay_days_home_max' => 3,
                'delay_days_away_max' => 3,
                'created_at' => '2021-09-01 22:38:13',
                'updated_at' => '2024-11-04 12:01:01',
                'last_login_at' => '2024-11-27 11:51:14',
            ],
            [
                'id' => 2154,
                'name' => 'Sparta Bobr',
                'first_name' => 'Stan',
                'last_name' => 'Decaluwé',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart Groen',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 3,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-10-18 14:54:45',
                'last_login_at' => '2024-11-26 11:55:36',
            ],
            [
                'id' => 2155,
                'name' => 'Allstar Legends',
                'first_name' => 'Dimitri',
                'last_name' => 'Rosseel',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Grijs',
                'shorts_color' => 'Grijs',
                'team_info' => 'Team onstaan door passie van voetbal',
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-10-13 23:06:59',
                'last_login_at' => '2024-11-23 22:07:19',
            ],
            [
                'id' => 2156,
                'name' => 'Zagros',
                'first_name' => 'Nima',
                'last_name' => 'Sayyedian',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Goudachtig geel',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-08-23 12:54:50',
                'last_login_at' => '2024-11-27 13:27:12',
            ],
            [
                'id' => 2157,
                'name' => 'Negenduust FC',
                'first_name' => 'Sedat',
                'last_name' => 'Kabak',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-11-22 12:18:54',
                'last_login_at' => '2024-11-26 20:06:42',
            ],
            [
                'id' => 1595,
                'name' => 'Erreché Inoxs',
                'first_name' => 'Robbe',
                'last_name' => 'Van Hecke',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'rood',
                'shorts_color' => 'zwart',
                'team_info' => "7 simpele vrienden met een passie voor voetbal en de 3e helft.\n\nOntstaan: Lang geleden... een licht beschonken avond... 7 vrienden met een voetbalverleden...\n\nRating: 0 Chemistry: 100\n\nDoel: Promoveren!!!",
                'delay_home_max' => 0,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2021-08-23 14:05:11',
                'updated_at' => '2023-04-06 23:51:03',
                'last_login_at' => '2024-11-22 14:41:45',
            ],
            [
                'id' => 1907,
                'name' => 'Sporting Lourdes',
                'first_name' => 'Gunnar',
                'last_name' => 'Vispoel',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Groen-Wit of Zwart-Groen',
                'shorts_color' => 'Wit of Zwart',
                'team_info' => "Zaalvoetbalploeg Chiro Lourdes\nhttps://instagram.com/sportinglourdes?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
                'delay_home_max' => 25,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 300,
                'created_at' => '2023-08-18 12:18:24',
                'updated_at' => '2024-11-02 10:45:21',
                'last_login_at' => '2024-11-26 23:15:13',
            ],
            [
                'id' => 961,
                'name' => 'KSA Sint Lieven',
                'first_name' => 'Miel',
                'last_name' => 'De Maesschalck',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'oranje/blauw',
                'shorts_color' => 'zwart of blauw',
                'team_info' => "VC KSA Sint-Lieven speelt intussen hun zevende seizoen in de LZV Cup. Met een kern van ervaren spelers aangevuld met aanstormend talent, gaan we elke wedstrijd vol overtuiging tegemoet. De voorbije seizoenen behaalden we enkele mooie resultaten en ook dit jaar kent onze ambitie geen grenzen. Plezier op en naast het veld staat steeds centraal en met de enthousiaste steun van onze trouwe supporters kijken we vol vertrouwen naar wat dit seizoen zal brengen!\n\nhttps://www.facebook.com/VCKSASintLieven/",
                'delay_home_max' => 3,
                'delay_days_home_max' => 7,
                'delay_days_away_max' => 5,
                'created_at' => '2018-08-23 00:08:11',
                'updated_at' => '2024-11-23 00:16:02',
                'last_login_at' => '2024-11-27 09:37:02',
            ],
            [
                'id' => 1709,
                'name' => 'Tattas FC',
                'first_name' => 'Rocco',
                'last_name' => 'Gueli',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 0,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 300,
                'created_at' => '2022-08-17 08:07:17',
                'updated_at' => '2023-09-22 15:57:46',
                'last_login_at' => '2024-11-25 00:21:51',
            ],
            [
                'id' => 964,
                'name' => 'P&V Youngboys',
                'first_name' => 'Olivier',
                'last_name' => 'De Gusseme',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Groen',
                'shorts_color' => 'Wit',
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 3,
                'created_at' => '2018-08-23 00:08:11',
                'updated_at' => '2024-10-25 09:14:26',
                'last_login_at' => '2024-11-26 13:00:16',
            ],
            [
                'id' => 1692,
                'name' => 'Atlético Waitabit',
                'first_name' => 'Jari',
                'last_name' => 'Van den Nest',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Wit',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 5,
                'delay_days_home_max' => 3,
                'delay_days_away_max' => 3,
                'created_at' => '2022-08-17 08:05:15',
                'updated_at' => '2024-09-08 08:54:28',
                'last_login_at' => '2024-11-26 14:32:30',
            ],
            [
                'id' => 1924,
                'name' => 'Aap MV',
                'first_name' => 'Douwe',
                'last_name' => 'Demetter',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'rood/zwart',
                'shorts_color' => 'zwart',
                'team_info' => null,
                'delay_home_max' => 5,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 5,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2024-03-25 12:06:51',
                'last_login_at' => '2024-11-25 11:11:29',
            ],
            [
                'id' => 1922,
                'name' => 'CF Biercelona',
                'first_name' => 'Andres',
                'last_name' => 'Goetmaekere',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Wit/Groen',
                'shorts_color' => 'Wit',
                'team_info' => "In onze voetbalploeg gaat het niet alleen om het spel zelf, maar ook om de reis die we samen maken. We zijn meer dan vijf individuen op het veld; we zijn een hechte eenheid die streeft naar uitmuntendheid en succes. Onze voetbalploeg belichaamt de geest van vastberadenheid, passie en saamhorigheid. Samen gaan we de uitdagingen aan, overwinnen we obstakels en zetten we stappen naar triomfantelijke hoogten.",
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2023-08-18 12:20:05',
                'updated_at' => '2023-08-26 15:56:53',
                'last_login_at' => '2024-11-26 21:56:12',
            ],
            [
                'id' => 2159,
                'name' => 'Interforza',
                'first_name' => 'Bart',
                'last_name' => 'Sautois',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Donkerblauw (met rood)',
                'shorts_color' => 'Donkerblauw (met rood)',
                'team_info' => "Ontstaan in seizoen 1998-1999, en nog altijd (grotendeels) dezelfde bende. Niet meer de jongste, maar  wel geroutineerd. Eens zien wat dat geeft, een eerste seizoen bij LZV in plaats van KBVB.",
                'delay_home_max' => 3,
                'delay_days_home_max' => 4,
                'delay_days_away_max' => 2,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-08-22 21:44:15',
                'last_login_at' => '2024-11-25 15:48:14',
            ],
            [
                'id' => 2160,
                'name' => 'FC Rikkie Techniekie',
                'first_name' => 'Goldey',
                'last_name' => 'Singh',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 5,
                'delay_days_home_max' => 21,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-09-25 10:40:49',
                'last_login_at' => '2024-11-25 20:57:24',
            ],
            [
                'id' => 2161,
                'name' => 'Shab Gent',
                'first_name' => 'Jeff',
                'last_name' => 'Den Blauwen',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Oranje',
                'shorts_color' => 'Zwart',
                'team_info' => null,
                'delay_home_max' => 1,
                'delay_days_home_max' => 28,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-10-09 17:47:11',
                'last_login_at' => '2024-11-27 12:35:54',
            ],
            [
                'id' => 2162,
                'name' => 'FC Cracking the UAV',
                'first_name' => 'Alexander',
                'last_name' => 'Samoise',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => null,
                'shorts_color' => null,
                'team_info' => null,
                'delay_home_max' => 3,
                'delay_days_home_max' => 5,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-10-09 14:40:36',
                'last_login_at' => '2024-11-22 11:42:06',
            ],
            [
                'id' => 2158,
                'name' => 'Malem United',
                'first_name' => 'Hicham',
                'last_name' => 'Bouyahiaoui',
                'email' => '***@***.***',
                'website' => null,
                'shirt_color' => 'Zwart Roze  / Lichtblauw',
                'shorts_color' => 'Zwart H - Grijs A',
                'team_info' => "Een mix van jong en oud opzoek naar glorie en promoties, startende club met een eerste ervaring in het zaalvoetbal! Een groep vrienden die samen groot dromen en hier met vol enthousiasme aan dit verhaal willen beginnen schrijven. Malem United!",
                'delay_home_max' => 3,
                'delay_days_home_max' => 300,
                'delay_days_away_max' => 7,
                'created_at' => '2024-08-17 09:41:20',
                'updated_at' => '2024-10-23 12:37:45',
                'last_login_at' => '2024-11-21 10:02:15',
            ],
        ];

        DB::table('teams')->insert($teams);
    }
}
